#!/bin/bash
# merge modis hdf datia
#
#   modis_merge input_directory output_directory
#
# if output directory is not specified, current directory is used
#
# /dev/shm is used by default for temporary files, which may not be big
# enough on desktop type machines, in which case /tmp may be a better option.

#--- variables:

# modis variable of interest:
MODIS_VAR='ET_500m'
MODIS_GRID='MOD_Grid_MOD16A2'
# temporary working directory:
TMP_DIR='/dev/shm'

#---

# get script directory:
SCRIPT_DIR=$(readlink -f $(dirname ${0}))

# get script name:
SCRIPT_NAME=$(basename ${0})

# usage function:
function usage() {
  echo "${SCRIPT_NAME} input_directory [output_directory]"
  exit
}

# error function:
function error() {
  echo "${1}"
  exit
}

# check input
if [ ${#} -lt 1 ] ; then
  usage
fi

# input directory:
INPUT_DIR=${1}

# check if output dir is specified:
if [ -z "${2}" ] ; then
  OUTPUT_DIR=$(pwd)
else
  OUTPUT_DIR=${2}
fi

# make output dir:
mkdir -p ${OUTPUT_DIR} || \
  error "Failed to create output directory ${OUTPUT_DIR}. Exiting"

# make tmp dir:
WORKING_DIR=${TMP_DIR}/.${SCRIPT_NAME}_$(date +%s)
mkdir ${WORKING_DIR} || \
  error "Failed to create directory ${WORKING_DIR}. Exiting"

# extract variable of interest from hdf files:
echo "#- $(date) : Extracting data from hdf files ... "
for hdf_file in ${INPUT_DIR}/MOD*.hdf
do
  file_name=$(basename ${hdf_file})
  geotiff_name=${file_name/.hdf/.tif}
  gdal_translate \
    -q \
    -of GTiff \
    -unscale \
    -a_nodata -9999 \
    -ot Float32 \
    HDF4_EOS:EOS_GRID:"${hdf_file}":${MODIS_GRID}:${MODIS_VAR} \
    ${WORKING_DIR}/${geotiff_name}
  # update nodata values. set everything > 32760 to 32767:
  ${SCRIPT_DIR}/modis_et_update_tif.py ${WORKING_DIR}/${geotiff_name}
done

# merge tifs:
echo "#- $(date) : Merging tiff files ... "
gdal_merge.py \
  -init -9999 \
  -n -9999 \
  -a_nodata -9999 \
  -o ${WORKING_DIR}/merged_00.tif \
  ${WORKING_DIR}/MOD*.tif

# convert to epsg:4326:
echo "#- $(date) : Reprojecting tiff ... "
echo "USING NEAREST NEIGHBOUR........"
gdalwarp \
  -co "BIGTIFF=YES" \
  -r average \
  -t_srs EPSG:4326 \
  -tr 0.05 0.05 \
  ${WORKING_DIR}/merged_00.tif \
  ${WORKING_DIR}/merged_01a.tif

# compress tif:
echo "#- $(date) : Compressing tiff ... "
gdalwarp \
  -co "BIGTIFF=YES" \
  -co "COMPRESS=LZW" \
  ${WORKING_DIR}/merged_01a.tif \
  ${WORKING_DIR}/merged_01.tif
  
# create netcdf file:
echo "#- $(date) : Creating NetCDF file ... "
gdal_translate \
  -of netCDf \
  ${WORKING_DIR}/merged_01.tif \
  ${WORKING_DIR}/merged_01a.nc

# compress netcdf file:
echo "#- $(date) : Compressing NetCDF file ... "
ncks \
  -h \
  -O \
  -4 \
  -L3 \
  --cnk_dmn Band1,4096 \
  --cnk_dmn lon,4096 \
  --cnk_dmn lat,4096 \
  ${WORKING_DIR}/merged_01a.nc \
  ${WORKING_DIR}/merged_01.nc

# copy files to output directory:
echo "#- $(date) : Copying output files ... "
cp \
  ${WORKING_DIR}/merged_01.tif \
  ${OUTPUT_DIR}/merged_0.05_average_interp_fix.tif
cp \
  ${WORKING_DIR}/merged_01.nc \
  ${OUTPUT_DIR}/merged_0.05_average_interp_fix.nc

# tidy:
cp ${WORKING_DIR}/* ${OUTPUT_DIR}/* 
\rm ${WORKING_DIR}/*
rmdir ${WORKING_DIR}

# done.
echo "#- $(date) : Done."
